version: 2

models:
  - name: silver_civic_genes
    description: "Silver layer for CIViC Genes"
    columns:
      - name: coreason_id
        description: "Primary Key (UUID)"
        tests:
          - unique
          - not_null
      - name: gene_id
        description: "Original Source ID"
        tests:
          - unique
          - not_null

  - name: silver_civic_variants
    description: "Silver layer for CIViC Variants"
    columns:
      - name: coreason_id
        description: "Primary Key (UUID)"
        tests:
          - unique
          - not_null
      - name: variant_id
        description: "Original Source ID"
        tests:
          - unique
          - not_null
      - name: gene_id
        description: "Foreign Key to Silver.CIViC_Genes"
        tests:
          - not_null
          - relationships:
              to: ref('silver_civic_genes')
              field: gene_id

  - name: silver_civic_evidence
    description: "Silver layer for CIViC Evidence"
    columns:
      - name: coreason_id
        description: "Primary Key (UUID)"
        tests:
          - unique
          - not_null
      - name: evidence_id
        description: "Original Source ID"
        tests:
          - unique
          - not_null
      - name: variant_id
        description: "Foreign Key to Silver.CIViC_Variants"
        tests:
          - not_null
          - relationships:
              to: ref('silver_civic_variants')
              field: variant_id
